import type { Batch, Student } from './types';

export const demoBatches: Batch[] = [
    {
        id: 'demo-batch-1',
        name: 'Morning Physics - Grade 12',
        location: 'Room 101',
        teacher: 'Dr. Evelyn Reed',
        time: '08:00',
        days: ['Mon', 'Wed', 'Fri'],
        maxSlots: 20,
        currentStudents: 3,
        batchFeeAmount: 500,
        batchFeeType: 'Monthly',
    },
    {
        id: 'demo-batch-2',
        name: 'Evening Maths - Grade 11',
        location: 'Room 203',
        teacher: 'Mr. Alan Grant',
        time: '17:30',
        days: ['Tue', 'Thu'],
        maxSlots: 15,
        currentStudents: 4,
        batchFeeAmount: 400,
        batchFeeType: 'Monthly',
    },
];

export const demoStudents: Student[] = [
    {
        id: 'demo-student-1',
        rollNumber: 'S001',
        name: 'Alice Johnson',
        fatherName: 'Robert Johnson',
        motherName: 'Mary Johnson',
        dob: '2006-05-15',
        mobile1: '9876543210',
        gender: 'Female',
        address: '123 Maple Street',
        admissionDate: '2023-04-01',
        batches: ['Morning Physics - Grade 12'],
        transport: 'NO_TRANSPORT_USE',
        isActive: true,
        feeAmount: 500,
        feeType: 'Monthly',
    },
    {
        id: 'demo-student-2',
        rollNumber: 'S002',
        name: 'Bob Williams',
        fatherName: 'James Williams',
        motherName: 'Patricia Williams',
        dob: '2006-08-22',
        mobile1: '9876543211',
        gender: 'Male',
        address: '456 Oak Avenue',
        admissionDate: '2023-04-02',
        batches: ['Morning Physics - Grade 12', 'Evening Maths - Grade 11'],
        transport: 'USE_TRANSPORT',
        isActive: true,
        feeAmount: 900,
        feeType: 'Monthly',
    },
    {
        id: 'demo-student-3',
        rollNumber: 'S003',
        name: 'Charlie Brown',
        fatherName: 'Charles Brown Sr.',
        motherName: 'Jennifer Brown',
        dob: '2007-02-10',
        mobile1: '9876543212',
        gender: 'Male',
        address: '789 Pine Lane',
        admissionDate: '2023-04-03',
        batches: ['Evening Maths - Grade 11'],
        transport: 'NO_TRANSPORT_USE',
        isActive: true,
        feeAmount: 400,
        feeType: 'Monthly',
    },
    {
        id: 'demo-student-4',
        rollNumber: 'S004',
        name: 'Diana Miller',
        fatherName: 'Michael Miller',
        motherName: 'Linda Miller',
        dob: '2006-11-30',
        mobile1: '9876543213',
        gender: 'Female',
        address: '101 Birch Road',
        admissionDate: '2023-04-05',
        batches: ['Morning Physics - Grade 12'],
        transport: 'NO_TRANSPORT_USE',
        isActive: true,
        feeAmount: 500,
        feeType: 'Monthly',
    },
    {
        id: 'demo-student-5',
        rollNumber: 'S005',
        name: 'Ethan Davis',
        fatherName: 'David Davis',
        motherName: 'Susan Davis',
        dob: '2007-01-20',
        mobile1: '9876543214',
        gender: 'Male',
        address: '212 Cedar Street',
        admissionDate: '2023-04-06',
        batches: ['Evening Maths - Grade 11'],
        transport: 'USE_TRANSPORT',
        isActive: true,
        feeAmount: 400,
        feeType: 'Monthly',
    },
    {
        id: 'demo-student-6',
        rollNumber: 'S006',
        name: 'Fiona Garcia',
        fatherName: 'Richard Garcia',
        motherName: 'Karen Garcia',
        dob: '2007-03-12',
        mobile1: '9876543215',
        gender: 'Female',
        address: '333 Elm Drive',
        admissionDate: '2023-04-10',
        batches: ['Evening Maths - Grade 11'],
        transport: 'NO_TRANSPORT_USE',
        isActive: true,
        feeAmount: 400,
        feeType: 'Monthly',
    },
];
